version: "3"

services:
  mysql_db_service:
    image: mysql:8.0.21
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "Pa$$WorD"
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - /home/mranonymous/Projects/Instagram-Volumes/mysql:/var/lib/mysql
      - ./mysql/:/docker-entrypoint-initdb.d

  mongo_db_service:
    image: mongo
    container_name: mongo_db
    restart: always
    volumes:
      - /home/mranonymous/Projects/Instagram-Volumes/mysql:/data/db
    ports:
      - '27017:27017'

  rabbitmq_service:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'

  api_gateway_service:
    build: ../backend/services/Instagram.ApiGateway
    container_name: api_gateway
    restart: always
    depends_on:
      - mysql_db_service
      - user_service
      - post_service
    ports:
      - '8000:8000'
    expose:
      - '8000'

  user_service:
    build: ../backend/services/Instagram.Services.User
    container_name: user
    restart: always
    expose:
      - '9000'
    depends_on:
      - mysql_db_service
      - rabbitmq_service

  post_service:
    build: ../backend/services/Instagram.Services.Post
    container_name: post
    restart: always
    expose:
      - '9001'
    volumes:
        - "/home/mranonymous/Pictures:/home/mranonymous/Pictures"
    depends_on:
      - mysql_db_service
      - user_service
      - azurite_service
      - rabbitmq_service

  azurite_service:
    image: "mcr.microsoft.com/azure-storage/azurite"
    container_name: azurite
    hostname: azurite
    restart: always
    volumes:
        - "/home/mranonymous/Projects/Instagram-Volumes/Azurite:/data"
        - "/home/mranonymous/Projects/Instagram-Volumes/Azurite/debug.log:/data/debug.log"
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"
    expose:
      - '10000'
      - '10001'
    ports:
    - 10000:10000
    - 10001:10001

volumes:
  mysql: